-- MySQL Script generated by MySQL Workbench
-- Sun Aug  6 16:36:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema zmap_v2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zmap_v2` ;

-- -----------------------------------------------------
-- Schema zmap_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zmap_v2` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `zmap_v2` ;

-- -----------------------------------------------------
-- Table `zmap_v2`.`container`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`container` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`container` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `short_name` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `marker_url` VARCHAR(250) NOT NULL DEFAULT '/markers/' COMMENT 'Each map can have a set of different markers icons just by changing the marker url',
  `marker_ext` CHAR(3) NOT NULL DEFAULT 'png' COMMENT '',
  `background_color` CHAR(7) NOT NULL DEFAULT '#DEECFD' COMMENT '',
  `show_street_view` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Only for googlemaps (for now)',
  `show_map_control` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '',
  `show_zoom_control` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '',
  `show_pan_control` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Only for googlemaps (for now)',
  `show_category_menu` TINYINT(1) NULL DEFAULT '1' COMMENT '',
  `default_pos_x` FLOAT NOT NULL DEFAULT '128' COMMENT '0 for googlemap, 128 for leaflet',
  `default_pos_y` FLOAT NOT NULL DEFAULT '-128' COMMENT '0 for googlemap, -128 for leaflet',
  `max_zoom` INT(2) NULL DEFAULT 6 COMMENT '',
  `cluster_max_zoom` INT(2) NOT NULL DEFAULT '4' COMMENT 'Max zoom to cluster the markers. Best -2 from the max zoom allowed (if 6 is the max, cluster should be 4)',
  `cluster_grid_size` INT(2) NOT NULL DEFAULT '30' COMMENT 'Pixel size of grid (default 30)',
  `tile_size` INT(3) NOT NULL DEFAULT '256' COMMENT 'Internet default is 256',
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'If map can be viewed',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `map_id_UNIQUE` ON `zmap_v2`.`container` (`id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE UNIQUE INDEX `short_name_UNIQUE` ON `zmap_v2`.`container` (`short_name` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`marker_category_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`marker_category_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`marker_category_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`marker_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`marker_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`marker_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `parent_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `marker_category_type_id` INT(11) NOT NULL COMMENT '',
  `container_id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `default_checked` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `img` VARCHAR(45) NOT NULL COMMENT '',
  `color` VARCHAR(45) NOT NULL DEFAULT '#000000' COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_marker_category_map_container1`
    FOREIGN KEY (`container_id`)
    REFERENCES `zmap_v2`.`container` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marker_category_marker_category_type1`
    FOREIGN KEY (`marker_category_type_id`)
    REFERENCES `zmap_v2`.`marker_category_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marker_category_marker_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `zmap_v2`.`marker_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_marker_category_map_container1_idx` ON `zmap_v2`.`marker_category` (`container_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_marker_category_marker_category_type1_idx` ON `zmap_v2`.`marker_category` (`marker_category_type_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_marker_category_marker_category1_idx` ON `zmap_v2`.`marker_category` (`parent_id` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`marker_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`marker_status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`marker_status` (
  `id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`map_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`map_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`map_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `projection` VARCHAR(45) NOT NULL COMMENT '',
  `google_default` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`mapper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`mapper` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`mapper` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `site_name` VARCHAR(45) NULL COMMENT '',
  `site_url` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`map`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`map` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`map` (
  `id` INT(11) NOT NULL COMMENT '',
  `container_id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `is_default` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `default_zoom` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '',
  `max_zoom` TINYINT(1) NOT NULL COMMENT '',
  `map_copyright` VARCHAR(250) NOT NULL COMMENT '',
  `map_order` TINYINT(2) NOT NULL COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_map_project1`
    FOREIGN KEY (`container_id`)
    REFERENCES `zmap_v2`.`container` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_map_project1_idx` ON `zmap_v2`.`map` (`container_id` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`submap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`submap` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`submap` (
  `id` INT(11) NOT NULL COMMENT '',
  `map_id` INT(11) NOT NULL COMMENT '',
  `map_type_id` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `mapper_id` INT(11) NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `is_default` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `tile_url` VARCHAR(250) NOT NULL COMMENT '',
  `tile_ext` CHAR(3) NOT NULL DEFAULT 'png' COMMENT '',
  `img404` VARCHAR(10) NOT NULL DEFAULT '404' COMMENT '',
  `submap_order` INT(11) NOT NULL DEFAULT '-1' COMMENT '',
  `empty_map` TINYINT(1) NOT NULL COMMENT '',
  `opacity` FLOAT NOT NULL DEFAULT 1 COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_map_game_map_type10`
    FOREIGN KEY (`map_type_id`)
    REFERENCES `zmap_v2`.`map_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_map_mapper10`
    FOREIGN KEY (`mapper_id`)
    REFERENCES `zmap_v2`.`mapper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submap_map1`
    FOREIGN KEY (`map_id`)
    REFERENCES `zmap_v2`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_map_game_map_type1_idx` ON `zmap_v2`.`submap` (`map_type_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_map_mapper1_idx` ON `zmap_v2`.`submap` (`mapper_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_submap_map1_idx` ON `zmap_v2`.`submap` (`map_id` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`marker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`marker` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`marker` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `submap_id` INT(11) NOT NULL COMMENT '',
  `overlay_id` INT(11) NULL COMMENT '',
  `marker_status_id` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `marker_category_id` INT(11) NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `name` TEXT NOT NULL COMMENT '',
  `description` TEXT NOT NULL COMMENT '',
  `x` DOUBLE NOT NULL COMMENT '',
  `y` DOUBLE NOT NULL COMMENT '',
  `jump_marker_id` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `global` TINYINT(1) NULL DEFAULT '0' COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `last_updated` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_map_marker_map_marker_category1`
    FOREIGN KEY (`marker_category_id`)
    REFERENCES `zmap_v2`.`marker_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_map_marker_map_marker_status1`
    FOREIGN KEY (`marker_status_id`)
    REFERENCES `zmap_v2`.`marker_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marker_submap1`
    FOREIGN KEY (`submap_id`)
    REFERENCES `zmap_v2`.`submap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marker_submap2`
    FOREIGN KEY (`overlay_id`)
    REFERENCES `zmap_v2`.`submap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_map_marker_map_marker_status1_idx` ON `zmap_v2`.`marker` (`marker_status_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_map_marker_map_marker_category1_idx` ON `zmap_v2`.`marker` (`marker_category_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_marker_submap1_idx` ON `zmap_v2`.`marker` (`submap_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_marker_submap2_idx` ON `zmap_v2`.`marker` (`overlay_id` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`marker_tab_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`marker_tab_status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`marker_tab_status` (
  `id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `created` DATETIME NOT NULL COMMENT '',
  `ip` VARCHAR(46) NOT NULL COMMENT '',
  `last_login` DATETIME NOT NULL COMMENT '',
  `level` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username_UNIQUE` ON `zmap_v2`.`user` (`username` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `zmap_v2`.`user` (`email` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`marker_tab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`marker_tab` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`marker_tab` (
  `marker_tab_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `marker_id` INT(11) NOT NULL COMMENT '',
  `marker_tab_status_id` INT(11) NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  `tab_title` VARCHAR(45) NOT NULL COMMENT '',
  `tab_text` TEXT NOT NULL COMMENT '',
  `tab_order` INT(11) NOT NULL DEFAULT '-1' COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`marker_tab_id`)  COMMENT '',
  CONSTRAINT `fk_map_marker_tab_map_marker1`
    FOREIGN KEY (`marker_id`)
    REFERENCES `zmap_v2`.`marker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_marker_tab_marker_tab_status1`
    FOREIGN KEY (`marker_tab_status_id`)
    REFERENCES `zmap_v2`.`marker_tab_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marker_tab_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `zmap_v2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_map_marker_tab_map_marker1_idx` ON `zmap_v2`.`marker_tab` (`marker_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_marker_tab_marker_tab_status1_idx` ON `zmap_v2`.`marker_tab` (`marker_tab_status_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_marker_tab_user1_idx` ON `zmap_v2`.`marker_tab` (`user_id` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `zmap_v2`.`submap_layer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zmap_v2`.`submap_layer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `zmap_v2`.`submap_layer` (
  `id` INT(11) NOT NULL COMMENT '',
  `submap_id` INT(11) NOT NULL COMMENT '',
  `mapper_id` INT(11) NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `tile_url` VARCHAR(250) NULL COMMENT '',
  `tile_ext` CHAR(3) NULL COMMENT '',
  `img404` VARCHAR(10) NULL COMMENT '',
  `control_visible` TINYINT(1) NULL COMMENT '\'If the layer can be visible on the layer control\'',
  `control_checked` TINYINT(1) NULL COMMENT '\'If the layer is default visible or not\'',
  `type` CHAR(1) NULL COMMENT '\'F - Foreground / B - Background\'',
  `layer_order` INT(11) NULL COMMENT '',
  `opacity` FLOAT NOT NULL DEFAULT 1 COMMENT '',
  `visible` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_map_layer_submap1`
    FOREIGN KEY (`submap_id`)
    REFERENCES `zmap_v2`.`submap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submap_layer_mapper1`
    FOREIGN KEY (`mapper_id`)
    REFERENCES `zmap_v2`.`mapper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_map_layer_submap1_idx` ON `zmap_v2`.`submap_layer` (`submap_id` ASC)  COMMENT '';

SHOW WARNINGS;
CREATE INDEX `fk_submap_layer_mapper1_idx` ON `zmap_v2`.`submap_layer` (`mapper_id` ASC)  COMMENT '';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `zmap_v2`.`marker_category_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `zmap_v2`;
INSERT INTO `zmap_v2`.`marker_category_type` (`id`, `name`, `visible`) VALUES (DEFAULT, 'Regular', 1);
INSERT INTO `zmap_v2`.`marker_category_type` (`id`, `name`, `visible`) VALUES (DEFAULT, 'Jump (Go To)', 1);
INSERT INTO `zmap_v2`.`marker_category_type` (`id`, `name`, `visible`) VALUES (DEFAULT, 'Label', 1);

COMMIT;

