INSERT INTO `marker_tab` VALUES
  (4075,12522,1,133521,'','&lt;p&gt;xcd&lt;/p&gt;',1,1),
  (4076,12584,1,142577,'','&lt;p&gt;Buried under the tree&lt;/p&gt;',1,1),
  (4077,12586,1,142525,'','&lt;p&gt;Side-quest involves defeating enemies on Aris Beach. Quest is given by Sebasto.&lt;/p&gt;',1,1),
  (4078,12587,1,142525,'','&lt;p&gt;Side quest involves fetching goat butter and a hearty blueshell snail for Kiana.&lt;/p&gt;',1,1),
  (4079,12594,1,142577,'','&lt;p&gt;Chest that appears at night where the red meteorite hit the ground.&lt;/p&gt;',1,1),
  (4080,12623,1,43876,'','&lt;p&gt;After 10 p.m, go to this house with 5 Sunset Fireflies&lt;/p&gt;',1,1),
  (4081,12629,1,145724,'','&lt;h1&gt;&lt;strong&gt;a&lt;/strong&gt;&lt;/h1&gt;',1,1),
  (4082,12630,1,43876,'','&lt;p&gt;Lezalfos with electric arrows&lt;/p&gt;',1,1),
  (4083,12651,1,147071,'','&lt;h4&gt;mounstroteca&lt;/h4&gt;',1,1),
  (4084,12651,1,147071,'','&lt;p style=&quot;text-align: center;&quot;&gt;mounstroteca&lt;/p&gt;',1,1),
  (4085,12654,1,147711,'','&lt;p&gt;suche&lt;/p&gt;',1,1),
  (4086,12721,1,137413,'','&lt;p&gt;Elle est l&#039;une des quatre&amp;nbsp;&lt;a title=&quot;Cr&amp;eacute;ature Divine&quot; href=&quot;https://zelda.fandom.com/fr/wiki/Cr%C3%A9ature_Divine&quot;&gt;Cr&amp;eacute;atures Divines&lt;/a&gt;, nomm&amp;eacute;e en r&amp;eacute;f&amp;eacute;rence &amp;agrave; la l&amp;eacute;gendaire&amp;nbsp;&lt;a title=&quot;Piaf&quot; href=&quot;https://zelda.fandom.com/fr/wiki/Piaf&quot;&gt;Piaf&lt;/a&gt;&amp;nbsp;&lt;a title=&quot;M&amp;eacute;dolie&quot; href=&quot;https://zelda.fandom.com/fr/wiki/M%C3%A9dolie&quot;&gt;M&amp;eacute;dolie&lt;/a&gt;. Vah&#039;Medoh est fabriqu&amp;eacute;e &amp;agrave; partir de la technologie&amp;nbsp;&lt;a title=&quot;Sheikah&quot; href=&quot;https://zelda.fandom.com/fr/wiki/Sheikah&quot;&gt;sheikah&lt;/a&gt;&amp;nbsp;et a une forme de condor.&amp;nbsp;&lt;a title=&quot;Ganon&quot; href=&quot;https://zelda.fandom.com/fr/wiki/Ganon&quot;&gt;Ganon&lt;/a&gt;&amp;nbsp;y a envoy&amp;eacute; l&#039;&lt;a title=&quot;Ombre de vent de Ganon&quot; href=&quot;https://zelda.fandom.com/fr/wiki/Ombre_de_vent_de_Ganon&quot;&gt;Ombre de vent de Ganon&lt;/a&gt;&amp;nbsp;comme assaillant de la Cr&amp;eacute;ature Divine Vah&#039;Medoh pour la corrompre, la faisant errer dans les airs et mena&amp;ccedil;ant les&amp;nbsp;&lt;a title=&quot;Confins de Tabanta&quot; href=&quot;https://zelda.fandom.com/fr/wiki/Confins_de_Tabanta&quot;&gt;Confins de Tabanta&lt;/a&gt;&amp;nbsp;jusqu&#039;&amp;agrave; ce que le d&amp;eacute;mon &amp;agrave; l&#039;int&amp;eacute;rieur soit tu&amp;eacute;.&lt;/p&gt;\r\n&lt;p&gt;La Cr&amp;eacute;ature Divine Vah&#039;Medoh corrompue fonctionne comme l&#039;un des principaux donjons dont le boss est l&#039;&lt;a title=&quot;Ombre de vent de Ganon&quot; href=&quot;https://zelda.fandom.com/fr/wiki/Ombre_de_vent_de_Ganon&quot;&gt;Ombre de vent de Ganon&lt;/a&gt;.&lt;/p&gt;',1,1),
  (4087,12739,1,154235,'','&lt;h1&gt;dsa&lt;/h1&gt;',1,1),
  (4088,12743,1,148976,'','&lt;p&gt;Talk to Sebasto and eliminate the enemies on Aris Beach.&lt;/p&gt;',1,1),
  (4089,12776,1,156560,'','&lt;p&gt;Lakna Rokee shrine&lt;/p&gt;',1,1),
  (4090,12777,1,156560,'','&lt;p&gt;Lakna Rokee shrine&lt;/p&gt;',1,1),
  (4091,12778,1,143174,'','&lt;p&gt;Common spot to farm Dinraal&#039;s pieces.&lt;/p&gt;',1,1),
  (4092,12851,1,160415,'','&lt;p&gt;Found near the two Lizalfos that spawn here. The sturdy construction of this bow offers superior durability, while its lack of firing quirks makes it highly reliable. Once favored by the knights at Hyrule Castle.&lt;/p&gt;',1,1),
  (4093,12852,1,160415,'','&lt;p&gt;Found near the two Lizalfos that spawn here. The sturdy construction of this bow offers superior durability, while its lack of firing quirks makes it highly reliable. Once favored by the knights at Hyrule Castle.&lt;/p&gt;',1,1),
  (4094,12885,1,164233,'','&lt;p&gt;Takama Shiri Shrine, aka Dual Purpose Shrine. Apart of the Champions Ballad DLC, and the EX Champion Urbosa&#039;s Song quest&lt;/p&gt;',1,1),
  (4095,12918,1,166028,'','&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;',1,1),
  (4096,12926,1,166147,'','&lt;p&gt;Speak to Lasli&lt;/p&gt;',1,1),
  (4097,12950,1,168259,'','&lt;div class=&quot;leaflet-popup-content-wrapper&quot;&gt;\r\n&lt;div class=&quot;leaflet-popup-content&quot;&gt;\r\n&lt;div class=&quot;zd-popup&quot;&gt;\r\n&lt;div class=&quot;zd-popup__body&quot;&gt;\r\n&lt;p&gt;&quot;A shirt with the Nintendo Switch logo on it. It&#039;s a rather rare find, so wear it with pride!&quot;&lt;/p&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;zd-popup__controls&quot;&gt;&amp;nbsp;&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;leaflet-popup-tip-container&quot;&gt;&amp;nbsp;&lt;/div&gt;',1,1),
  (4098,12956,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4099,12957,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4100,12958,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4101,12959,1,2534,'','&lt;p&gt;&lt;em&gt;Stop to Start&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Activate the Divine Beast Tamer&#039;s Trial&lt;/p&gt;',1,1),
  (4102,12960,1,2534,'','&lt;p&gt;&lt;em&gt;Collected Soul&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Activate the Divine Beast Tamer&#039;s Trial&lt;/p&gt;',1,1),
  (4103,12961,1,2534,'','&lt;p&gt;&lt;em&gt;A Major Test of Strength+&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Activate the Divine Beast Tamer&#039;s Trial&lt;br /&gt;&lt;strong&gt;Enemies:&lt;/strong&gt;&amp;nbsp;&lt;a title=&quot;Guardian Scout I&quot; href=&quot;https://www.zeldadungeon.net/wiki/Guardian_Scout_I&quot;&gt;Guardian Scout I&lt;/a&gt;&lt;br /&gt;&lt;a title=&quot;Guardian Scout III&quot; href=&quot;https://www.zeldadungeon.net/wiki/Guardian_Scout_III&quot;&gt;Guardian Scout III&lt;/a&gt;&lt;br /&gt;&lt;a title=&quot;Guardian Scout IV&quot; href=&quot;https://www.zeldadungeon.net/wiki/Guardian_Scout_IV&quot;&gt;Guardian Scout IV&lt;/a&gt;&lt;/p&gt;',1,1),
  (4104,12962,1,2534,'','&lt;p&gt;&lt;em&gt;Path of Light&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Activate the Divine Beast Tamer&#039;s Trial&lt;br /&gt;&lt;strong&gt;Enemies:&lt;/strong&gt;&amp;nbsp;&lt;a title=&quot;Guardian Scout I&quot; href=&quot;https://www.zeldadungeon.net/wiki/Guardian_Scout_I&quot;&gt;Guardian Scout I&lt;/a&gt;&lt;/p&gt;',1,1),
  (4105,12963,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4106,12964,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4107,12965,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4108,12966,1,2534,'','&lt;p&gt;&lt;em&gt;The Four Winds&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4109,12967,1,2534,'','&lt;p&gt;&lt;em&gt;Master the Orb&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4110,12968,1,2534,'','&lt;p&gt;&lt;em&gt;Aim for Stillness&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4111,12969,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau, and defeat the fire Titan&lt;/p&gt;',1,1),
  (4112,12970,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4113,12971,1,2534,'','&lt;p&gt;&lt;strong&gt;Requirements:&lt;/strong&gt;&amp;nbsp;Complete the four additional Shrines on the Great Plateau&lt;/p&gt;',1,1),
  (4114,12987,1,169063,'','&lt;p&gt;in the ground: no&lt;/p&gt;',1,1),
  (4115,13002,1,100450,'','&lt;p&gt;The start of the maze path to the shrine.&amp;nbsp;&lt;/p&gt;\r\n&lt;p&gt;Climb the maze walls, drop into this area, and face north and climb the ladder.&lt;/p&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;',1,1),
  (4116,13003,1,100450,'','&lt;p&gt;The entrance to the shrine chamber.&amp;nbsp; Get to this point in the maze and climb the ladder to the East.&lt;/p&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;',1,1),
  (4117,13004,1,100450,'','&lt;p&gt;At this point in the chamber beneath the shrine room, a chest at the back of the dead guardian room contains the travel medallion.&lt;/p&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n&lt;p&gt;Don&#039;t worry, unlike the Diamond Circlet chest, opening this one won&#039;t proc the guardians to evaporate you.&lt;/p&gt;',1,1),
  (4118,13005,1,100450,'','&lt;p&gt;PlaceHolder PlaceHolder PlaceHolder&lt;/p&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;',1,1),
  (4119,13006,1,171506,'','&lt;p&gt;The final boss (phase 1).&lt;/p&gt;',1,1),
  (4120,13007,1,100450,'','&lt;p&gt;Start of the path to the shrine chamber.&amp;nbsp; Stand here, face west, and&amp;nbsp; turn right at the malice and follow the path to the shrine.&lt;/p&gt;',1,1),
  (4121,13008,1,100450,'','&lt;p&gt;Underwater in the cave at the far East of Cora Lake. Use cryonis to get into magnesis range of it.&lt;/p&gt;\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;',1,1),
  (4122,13058,1,175007,'','&lt;p&gt;Talk to the woman behind the counter at the arrow shop, and she&#039;ll give you thiss quest.&lt;/p&gt;',1,1),
  (4123,13076,1,177263,'','&lt;p&gt;To gain Knight Gear in Horseback Archery Mini Game&lt;/p&gt;',1,1),
  (4124,13081,1,177583,'','&lt;p&gt;Kill 2 guardins down in the autumn forest just across the river.&lt;/p&gt;\r\n&lt;p&gt;Reward: Silver rupee (upon recieving the quest), Red (upon completion)&lt;/p&gt;',1,1),
  (4125,13082,1,177583,'','&lt;p&gt;After completing &quot;Robbies Research&quot; Side Quest, trade ancient materials with cherry for ancient soldier gear&lt;/p&gt;',1,1),
  (4126,13083,1,177583,'','&lt;p&gt;Must complete before all of tarrey town is accesable.&lt;/p&gt;\r\n&lt;p&gt;Requires completion of the &quot;Hylian Homeowner&quot; side quest.&lt;/p&gt;\r\n&lt;p&gt;Reward: 3 Diamonds&lt;/p&gt;',1,1),
  (4127,13084,1,177583,'','&lt;p&gt;Must complete &quot;A Shady Customer&quot; side quest for him to appear.&lt;/p&gt;\r\n&lt;p&gt;Only there at nighttime.&lt;/p&gt;',1,1),
  (4128,13107,1,154162,'','&lt;p&gt;F&amp;uuml;r die Quest wird eine Eldra Schuppe ben&amp;ouml;tigt, welche von dem Feuerdrachen z.B. mit einem Feuer- oder Bombenpfeil abgeschossen werden muss&lt;/p&gt;',1,1),
  (4129,13117,1,177629,'','&lt;p&gt;Aim for Stillness (DLC2)&lt;/p&gt;',1,1),
  (4130,13138,1,178755,'','&lt;p&gt;eafesfeazf&lt;/p&gt;',1,1),
  (4131,13162,1,170164,'','&lt;p&gt;NPC: Tumbo&lt;/p&gt;',1,1),
  (4132,13229,1,189803,'','&lt;p&gt;&lt;strong&gt;dffd&lt;/strong&gt;&lt;/p&gt;',1,1),
  (4133,13242,1,190222,'','&lt;h1&gt;&amp;nbsp;&lt;/h1&gt;',1,1),
  (4134,13247,1,192632,'','&lt;p&gt;A divine beast located in gerudo desert&lt;/p&gt;',1,1),
  (4135,13280,1,195117,'','&lt;p&gt;Red Rupee&lt;/p&gt;',1,1)
;
